title: SURVIVAL GUIDE
author: Girls Support Girls 
description: > # this means to ignore newlines until "baseurl:"
  Girls Support Girls: É um coletivo de garotas estudantes do Departamento de 
  Ciência da Computação (Matemática Computacional, Sistemas de Informação e Ciência
  da Computação) que tem o objetivo de tornar a computação cada vez mais acessível 
  para todas as pessoas. Incentivando e dando suporte principalmente as garotas estudantes
  na área STEM (Science, technology, engineering, and mathematics). 

# social links
# social links
twitter_username: 
github_username: 
instagram_username: 
facebook_username: https://www.facebook.com/groups/girlssupportgirls.ufmg/

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
